// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzQEmL-62bvsyotfwsW41rTpnmdJ1Zf1U',
    appId: '1:1022613728924:web:348db2a2ccbf8cb8dd0759',
    messagingSenderId: '1022613728924',
    projectId: 'agrovia-db202',
    authDomain: 'agrovia-db202.firebaseapp.com',
    storageBucket: 'agrovia-db202.firebasestorage.app',
    measurementId: 'G-P35MBRVS5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1b4I_urvda9qprAFM7NLeGQe9mcsxFOw',
    appId: '1:1022613728924:android:828f53cd2297bf82dd0759',
    messagingSenderId: '1022613728924',
    projectId: 'agrovia-db202',
    storageBucket: 'agrovia-db202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF6LgKoNq8O05S8O2RFbZpp9F7PDG96KU',
    appId: '1:1022613728924:ios:1dc1533ad973085bdd0759',
    messagingSenderId: '1022613728924',
    projectId: 'agrovia-db202',
    storageBucket: 'agrovia-db202.firebasestorage.app',
    iosBundleId: 'com.agrovia.agrovia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF6LgKoNq8O05S8O2RFbZpp9F7PDG96KU',
    appId: '1:1022613728924:ios:1dc1533ad973085bdd0759',
    messagingSenderId: '1022613728924',
    projectId: 'agrovia-db202',
    storageBucket: 'agrovia-db202.firebasestorage.app',
    iosBundleId: 'com.agrovia.agrovia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzQEmL-62bvsyotfwsW41rTpnmdJ1Zf1U',
    appId: '1:1022613728924:web:b41ae5610b1f23b1dd0759',
    messagingSenderId: '1022613728924',
    projectId: 'agrovia-db202',
    authDomain: 'agrovia-db202.firebaseapp.com',
    storageBucket: 'agrovia-db202.firebasestorage.app',
    measurementId: 'G-Q9Q37E8KMD',
  );
}
